### ISSUE TITLE
Rework Footer

### ISSUE THREAD

**Issue by vexy** [vexy/infoportal-website#23]
Add following footer items:
 - [x] created by Vex (in serbia)
 - [x] link to source
 - [x] vexy/infoportal-website#29 

Social share buttons:
- [x] vexy/infoportal-website#26 
- [x] vexy/infoportal-website#24
